### PR TITLE
Ap tb edit profile page

### LINKED ISSUE #123: TB  — Edit Profile Page
We need an edit profile page that's styled like the rest of the site, with some way to easily reach it. 

Click profile picture: Dropdown Menu to edit profile and sign out. 

Edit profile page works for all accounts.

### PR DESCRIPTION
**Pull request by APatel-AI**
https://github.com/user-attachments/assets/0c530bcc-f5a2-4d7a-ab2a-bb7fbed4912d

Screen Shot 2024-11-09 at 4 15 48 PM
Screen Shot 2024-11-09 at 4 17 17 PM

closes #123

### CODE REVIEW

**Review by borvux — APPROVED** [review]
Looks great!

**Review by rezahusain — APPROVED** [review]
Nice job Arpan :) approved!

**Review by borvux — APPROVED** [review]
Awesome!

**Review by rezahusain — APPROVED** [review]
Looks good!

**Pull request merged**
