### PR TITLE
112 ta mobile nav

### PR DESCRIPTION
**Pull request by YoungSong99**
Screenshot 2024-10-29 at 4 32 29 AM

mobile nav for landing and dashboard

### CODE REVIEW

**Review by MayaS1111 — APPROVED** [review]
Love it

**Review by rezahusain — APPROVED** [review]
Love how it looks on mobile! Approved :)

**Review by rezahusain — APPROVED** [review]
Looks really good Young! Approved.

**Review by SaraDawner2000 — APPROVED** [review]
Looks good 👍

**Pull request merged**
